name: curahead_app
description: "A teleconsultation application focused on connecting therapists with patients live using a mobile application."

publish_to: 'none'  # Prevents accidental publishing to pub.dev

version: 1.0.0+1  # Version of the app (major.minor.patch+build)

environment:
  sdk: ^3.5.3  # Specifies the Dart SDK version requirement

dependencies:
  flutter:
    sdk: flutter  # The Flutter SDK

  # Firebase dependencies for backend services
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  google_sign_in: ^6.0.0

  # State management package
  provider: ^6.0.5

  # iOS style icons (optional)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter  # For running Flutter tests

  # Linter package to enforce coding standards
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  # Enables the use of Material Icons in the app
  assets:
    - assets/icons/  # Custom assets like icons

